name: hello-world
on:
  push:
    paths:
    branches: 
  pull_request:
    types: [opened, synchronize, reopened,labeled, unlabeled]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 0
          labels: "do not build"
      - run: echo "TODAY=$(date)" >> $GITHUB_ENV
      - run: echo "Today is $TODAY"
